title: Zifan Song's Homepage
page-top-title: Zifan Song(宋子凡)
top-section-bg-text: Materials Science & Engineering 
home-subtitle: Zifan Song&ensp;|&ensp;宋子凡
copyright-text: '&copy; Zifan Song 2023-2025. All Rights Reserved.'